# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"create_path": "utils.utils.ipynb",
         "DATA_PATH": "config.ipynb",
         "MODEL_PATH": "config.ipynb",
         "LR": "config.ipynb",
         "TRAIN_BATCH_SIZE": "config.ipynb",
         "VALID_BATCH_SIZE": "config.ipynb",
         "NUM_EPOCHS": "en_task.en_task2.ipynb",
         "MAX_LEN": "config.ipynb",
         "MODEL_NAME": "config.ipynb",
         "DEVICE": "config.ipynb",
         "TOKENIZER": "config.ipynb",
         "df": "en_task.en_task2.ipynb",
         "y": "create_folds.ipynb",
         "kf": "create_folds.ipynb",
         "BertDataset": "dataset.dataset.ipynb",
         "SEED": "en_task.en_task2.ipynb",
         "le": "en_task.en_task2.ipynb",
         "train_dl": "en_task.en_task2.ipynb",
         "valid_dl": "en_task.en_task2.ipynb",
         "modeller": "en_task.en_task2.ipynb",
         "model_params": "en_task.en_task2.ipynb",
         "no_decay": "en_task.en_task2.ipynb",
         "optimizer_params": "en_task.en_task2.ipynb",
         "lr": "en_task.en_task2.ipynb",
         "optimizer": "en_task.en_task2.ipynb",
         "num_train_steps": "en_task.en_task2.ipynb",
         "scheduler": "en_task.en_task2.ipynb",
         "fit": "en_task.en_task2.ipynb",
         "test_df": "en_task.en_task2.ipynb",
         "test_dl": "en_task.en_task2.ipynb",
         "preds": "en_task.en_task2.ipynb",
         "sub": "en_task.en_task2.ipynb",
         "submission_en_task1_df": "en_task.en_task1.ipynb",
         "train_ds": "en_task.en_task2.ipynb",
         "submission_en_task2_df": "en_task.en_task2.ipynb",
         "HasocModel": "model.model.ipynb",
         "Fitter": "utils.engine.ipynb",
         "BertFitter": "utils.engine.ipynb",
         "get_preds": "utils.engine.ipynb",
         "seed_everything": "utils.utils.ipynb",
         "create_loader": "utils.utils.ipynb",
         "LabelSmoothingCrossEntropy": "utils.utils.ipynb"}

modules = ["config.py",
           "create_folds.py",
           "dataset/dataset.py",
           "en_task/en_task1.py",
           "en_task/en_task2.py",
           "model/model.py",
           "utils/engine.py",
           "utils/utils.py"]

doc_url = "https://Mani, Tendo.github.io/Hasoc/"

git_url = "https://github.com/Mani, Tendo/Hasoc/tree/master/"

def custom_doc_links(name): return None
