# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"MODEL_NAME": "main.ipynb",
         "MAX_SEQ_LEN": "main.ipynb",
         "device": "main.ipynb",
         "df": "main.ipynb",
         "df.tweet_id": "main.ipynb",
         "bert_tokenizer": "main.ipynb",
         "pad": "main.ipynb",
         "custom_tokenizer": "main.ipynb",
         "tfms": "main.ipynb",
         "splits": "main.ipynb",
         "dsets": "main.ipynb",
         "dls_clas": "main.ipynb",
         "model": "main.ipynb",
         "learn": "main.ipynb",
         "HasocModel": "model.ipynb",
         "bert_cls_splitter": "utils.ipynb",
         "HFTokenizer": "utils.ipynb",
         "Add_Special_Cls": "utils.ipynb"}

modules = ["main.py",
           "model.py",
           "utils.py"]

doc_url = "https://Mani, Tendo.github.io/Hasoc/"

git_url = "https://github.com/Mani, Tendo/Hasoc/tree/master/"

def custom_doc_links(name): return None
